SET(CMAKE_SYSTEM_NAME i486-mingw32)
SET(CMAKE_SYSTEM_VERSION 1)

SET(CMAKE_C_COMPILER i486-mingw32-gcc)
SET(CMAKE_CXX_COMPILER i486-mingw32-g++)

#SET(CMAKE_FIND_ROOT_PATH /usr/i486-mingw32:${CMAKE_FIND_ROOT_PATH})

#set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
#set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
#set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

